In [1]:
'''the difference betweem one-dimensional array---shape = (n,)
   and column or row vector---shape=(m,nn)
   we should avoid using one-dimensional array, 
   because it is not a vector'''
import numpy as np

a = np.random.randn(5)
print(a)

[ 0.66379238  1.18703379 -1.38848347 -0.40301448 -0.17151512]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[ 0.66379238  1.18703379 -1.38848347 -0.40301448 -0.17151512]


In [4]:
aT = a.T
print(aT.shape)

(5,)


In [5]:
print(np.dot(a, aT))

3.9693940095804887


In [6]:
import numpy as np

a = np.random.randn(5, 1)
print(a)

[[-0.30118156]
 [-0.0265626 ]
 [-0.03915363]
 [-0.41698134]
 [ 0.69815453]]


In [7]:
print(a.shape)

(5, 1)


In [8]:
print(a.T)

[[-0.30118156 -0.0265626  -0.03915363 -0.41698134  0.69815453]]


In [9]:
aT = a.T
print(aT.shape)

(1, 5)


In [10]:
print(np.dot(a, aT))

[[ 0.09071033  0.00800016  0.01179235  0.12558709 -0.21027127]
 [ 0.00800016  0.00070557  0.00104002  0.01107611 -0.0185448 ]
 [ 0.01179235  0.00104002  0.00153301  0.01632633 -0.02733529]
 [ 0.12558709  0.01107611  0.01632633  0.17387343 -0.29111741]
 [-0.21027127 -0.0185448  -0.02733529 -0.29111741  0.48741974]]
