In [9]:
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
print(tf.__version__)


2.4.0


In [17]:
print(tf.config.list_physical_devices('GPU'))


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [7]:



tf.random.set_seed(0)
tensor = tf.random.uniform([1000, 1000])
result = tf.matmul(tensor, tf.transpose(tensor))
print(result)

tf.Tensor(
[[323.3636  242.26758 247.74321 ... 243.57253 240.74985 248.18108]
 [242.26758 331.87793 253.15417 ... 245.6203  244.81635 258.34937]
 [247.74321 253.15417 338.92386 ... 255.94273 248.80397 257.96732]
 ...
 [243.57253 245.6203  255.94273 ... 330.47473 239.46445 257.59903]
 [240.74985 244.81635 248.80397 ... 239.46445 327.18317 250.94493]
 [248.18108 258.34937 257.96732 ... 257.59903 250.94493 340.65466]], shape=(1000, 1000), dtype=float32)


In [21]:
gpu_device = '/device:GPU:0'

with tf.device(gpu_device):
    # 在GPU上执行的操作
    a = tf.random.uniform([10000, 10000], dtype=tf.float32)
    b = tf.random.uniform([10000, 10000], dtype=tf.float32)
    c = tf.matmul(a, b)

# 打印结果
print(c)

tf.Tensor(
[[2513.1128 2516.7095 2478.8862 ... 2481.6472 2491.4343 2470.2815]
 [2519.4856 2528.8167 2507.1907 ... 2481.2095 2500.4177 2487.4302]
 [2502.1182 2498.3486 2452.7007 ... 2456.582  2464.8296 2449.35  ]
 ...
 [2572.9487 2571.877  2551.061  ... 2523.4143 2541.538  2524.5696]
 [2558.088  2530.0889 2497.8032 ... 2503.9473 2501.7656 2492.2876]
 [2521.7166 2512.0212 2484.7183 ... 2461.546  2485.1335 2479.9802]], shape=(10000, 10000), dtype=float32)
